version: '1.0'
services:
  db:
    container_name: 'filmDB_BA'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=filmdbuser
      - POSTGRES_PASSWORD=filmpasswd
    ports:
      - '5432:5432'
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
  jaeger:
    container_name: 'jaeger'
    platform: linux/amd64
    image: jaegertracing/all-in-one:1.19
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:v2.22.2
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    container_name: 'grafana'
    image: grafana/grafana:9.1.6
    ports:
      - 3000:3000
    restart: unless-stopped