{
 "title": "OtelDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "DotNet Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocation in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exception Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count{instance=\"host.docker.internal:9464\"}",
     "legendFormat": "OrderService"
    },
    {
     "expr": "process_runtime_dotnet_exceptions_count{instance=\"host.docker.internal:1234\"}",
     "legendFormat": "InventoryService"
    }
   ]
  },
  { "title": "Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Http Request Count GET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{http_method=\"GET\", http_route=\"orders\", http_status_code=\"200\"}",
     "legendFormat": "GET /orders"
    },
    {
     "expr": "http_server_duration_ms_count{http_route=\"orders/{orderId}\", http_method=\"GET\", http_status_code=\"200\"}",
     "legendFormat": "GET /orders/{orderID}"
    }
   ]
  },
  {
   "title": "Http Request Count GET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{http_route=\"products\", http_method=\"GET\", http_status_code=\"200\"}",
     "legendFormat": "GET /products"
    },
    {
     "expr": "http_server_duration_ms_count{http_method=\"GET\", http_route=\"products/{productId}\"}",
     "legendFormat": "GET /products/{productID}"
    }
   ]
  },
  {
   "title": "Http Requests Count GET /verify/{productID}/{quantity}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{http_route=\"verify/{productId}/{quantity}\", http_method=\"GET\", http_status_code=\"200\"}",
     "legendFormat": "GET /verify/{productID}/{quantity}"
    }
   ]
  },
  {
   "title": "Http Requests Count POST",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{http_method=\"POST\", http_route=\"orders\", http_status_code=\"201\"}",
     "legendFormat": "POST /orders"
    },
    {
     "expr": "http_server_duration_ms_count{http_method=\"POST\", http_route=\"products/{productId}/{quantity}\", http_status_code=\"200\"}",
     "legendFormat": "POST /products/{productID}/{quantity}"
    }
   ]
  },
  {
   "title": "Http Requests Count DELETE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{http_method=\"DELETE\", http_route=\"orders/{orderId}\"}",
     "legendFormat": "DELETE /orders/{orderID}"
    }
   ]
  },
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Distribution of the price of the orders",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "orders_price_Euros_bucket{instance=\"host.docker.internal:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inventory",
   "type": "gauge",
   "description": "Gauge representing the count of total Inventory",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_inventory_count{instance=\"host.docker.internal:1234\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Updated Products",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "products_updated_Product{instance=\"host.docker.internal:1234\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "gauge",
   "description": "Gauge representing the count of total orders",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_orders{instance=\"host.docker.internal:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of number of products per order",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "orders_number_of_products_Product_bucket{instance=\"host.docker.internal:9464\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}